# .github/workflows/hourly_run.yml
name: Run Readwise RSS Cleaner Hourly

on:
  schedule:
    # Runs "at minute 0 past every hour" (e.g., 1:00, 2:00, 3:00)
    # See https://crontab.guru/ for cron syntax help
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  run_script:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 # Action to get your code

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python src/main.py
        env:
          READWISE_API_TOKEN: ${{ secrets.READWISE_API_TOKEN }}
          GITHUB_GIST_ID: ${{ secrets.GITHUB_GIST_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
